//! Qwen2.5 parity: greedy sequence vs a local Ollama fp16 reference of the
//! SAME weights (`qwen2.5:1.5b-instruct-fp16` — the fp16 GGUF conversion of
//! the Qwen2.5-1.5B-Instruct checkpoint we load from safetensors). Ignored by
//! default; run with
//!
//! ```text
//! MUMMU_QWEN2_DIR=path/to/qwen2.5-1.5b cargo test -p mummu --release --test parity_qwen2 -- --ignored --nocapture
//! ```
//!
//! This is the greedy leg of the P7 parity gate; the top-k-logits leg runs
//! against the Candle probe (`tools/candle-probe`) which exposes raw logits.

use std::path::PathBuf;
use std::process::Command;

use mummu::backend::Gpu;
use mummu::models::CausalLm;
use mummu::models::qwen2;
use tokenizers::Tokenizer;

const REFERENCE_TAG: &str = "qwen2.5:1.5b-instruct-fp16";
const PROMPT: &str = "List the first five prime numbers.";
const MAX_TOKENS: usize = 24;

fn qwen2_dir() -> Option<PathBuf> {
    let dir = PathBuf::from(std::env::var_os("MUMMU_QWEN2_DIR")?);
    dir.is_dir().then_some(dir)
}

/// The Qwen2.5-Instruct ChatML wrapping (system + user turn + assistant open),
/// rendered by the library's own template — the fixture equality assert below
/// is what byte-verifies `chat::ChatMl::qwen2` against the Candle reference.
fn chatml(user: &str) -> String {
    mummu::chat::ChatMl::qwen2().render(&[
        mummu::chat::Turn::system("You are a helpful assistant."),
        mummu::chat::Turn::user(user),
    ])
}

/// Greedy reference from Ollama in raw mode (identical prompt text,
/// temperature 0), via curl so the test needs no HTTP dependency.
fn ollama_greedy(raw_prompt: &str, max_tokens: usize) -> Result<String, String> {
    let body = serde_json::json!({
        "model": REFERENCE_TAG,
        "prompt": raw_prompt,
        "raw": true,
        "stream": false,
        "options": { "temperature": 0.0, "num_predict": max_tokens }
    });
    let out = Command::new("curl")
        .args([
            "-s",
            "-X",
            "POST",
            "http://localhost:11434/api/generate",
            "-d",
        ])
        .arg(body.to_string())
        .output()
        .map_err(|e| format!("curl spawn: {e}"))?;
    if !out.status.success() {
        return Err(format!("curl exit {:?}", out.status.code()));
    }
    let v: serde_json::Value =
        serde_json::from_slice(&out.stdout).map_err(|e| format!("ollama response parse: {e}"))?;
    v.get("response")
        .and_then(|r| r.as_str())
        .map(str::to_string)
        .ok_or_else(|| format!("no response field in: {v}"))
}

/// The committed Candle reference (generated by `tools/candle-probe`; see its
/// header for the refresh command).
const LOGITS_FIXTURE: &str = include_str!("fixtures/qwen2_5_1_5b_first_logits.json");

/// Max |Δlogit| tolerated between Burn (wgpu f32) and Candle (CPU f32) on the
/// same weights: different backends legitimately reorder float reductions.
/// Measured on the dev GPU (4070 Ti SUPER, Vulkan): 2.7e-5 — this bound gives
/// ~40x headroom; anything past it is a real numeric bug, not noise.
const LOGIT_ABS_TOLERANCE: f32 = 1.0e-3;

#[test]
#[ignore = "needs local Qwen2.5 weights (MUMMU_QWEN2_DIR)"]
fn qwen2_first_forward_top_k_matches_candle_reference() {
    let Some(dir) = qwen2_dir() else {
        panic!("set MUMMU_QWEN2_DIR to a dir with config.json/tokenizer.json/model.safetensors");
    };
    let fixture: serde_json::Value = serde_json::from_str(LOGITS_FIXTURE).expect("fixture parses");

    // The fixture must have been generated from the *same rendered prompt*;
    // fail loudly on drift instead of comparing apples to oranges.
    let raw = chatml(PROMPT);
    assert_eq!(
        fixture["prompt_raw"].as_str().expect("prompt_raw"),
        raw,
        "fixture prompt drifted from the test prompt — regenerate with tools/candle-probe"
    );

    let tok = Tokenizer::from_file(dir.join("tokenizer.json")).expect("tokenizer.json loads");
    let prompt_ids = tok
        .encode(raw.as_str(), false)
        .expect("encodes")
        .get_ids()
        .to_vec();
    let fixture_ids: Vec<u32> = fixture["prompt_ids"]
        .as_array()
        .expect("prompt_ids")
        .iter()
        .map(|v| v.as_u64().expect("id") as u32)
        .collect();
    assert_eq!(prompt_ids, fixture_ids, "tokenizations diverge");

    let device = burn::tensor::Device::<Gpu>::default();
    let loaded = qwen2::load_from_dir::<Gpu>(&dir, &device).expect("weights load checked");
    let mut cache = loaded.new_cache();
    let logits = loaded
        .forward(&prompt_ids, 0, &mut cache, &device)
        .into_data()
        .convert::<f32>()
        .to_vec::<f32>()
        .expect("logits readback");

    let expected: Vec<(usize, f32)> = fixture["top_k"]
        .as_array()
        .expect("top_k")
        .iter()
        .map(|e| {
            (
                e["id"].as_u64().expect("id") as usize,
                e["logit"].as_f64().expect("logit") as f32,
            )
        })
        .collect();
    assert!(expected.len() >= 5, "fixture needs at least top-5");

    let mut indexed: Vec<(usize, f32)> = logits.iter().copied().enumerate().collect();
    indexed.sort_by(|a, b| b.1.total_cmp(&a.1));
    let ours = &indexed[..expected.len()];

    let our_ids: Vec<usize> = ours.iter().map(|&(id, _)| id).collect();
    let ref_ids: Vec<usize> = expected.iter().map(|&(id, _)| id).collect();
    let max_abs_diff = ours
        .iter()
        .zip(expected.iter())
        .map(|(&(_, a), &(_, b))| (a - b).abs())
        .fold(0.0_f32, f32::max);
    eprintln!("[parity/qwen2] top-{} ids ours: {our_ids:?}", ours.len());
    eprintln!("[parity/qwen2] top-{} ids ref : {ref_ids:?}", ours.len());
    eprintln!("[parity/qwen2] max |Δlogit| vs candle: {max_abs_diff:e}");

    assert_eq!(
        our_ids, ref_ids,
        "top-k ids diverge from the Candle reference"
    );
    assert!(
        max_abs_diff <= LOGIT_ABS_TOLERANCE,
        "logits diverge: max |Δ| = {max_abs_diff} > {LOGIT_ABS_TOLERANCE}"
    );
}

#[test]
#[ignore = "needs local Qwen2.5 weights (MUMMU_QWEN2_DIR) + a running Ollama with qwen2.5:1.5b-instruct-fp16"]
fn qwen2_greedy_sequence_matches_ollama_reference() {
    let Some(dir) = qwen2_dir() else {
        panic!("set MUMMU_QWEN2_DIR to a dir with config.json/tokenizer.json/model.safetensors");
    };
    let raw = chatml(PROMPT);

    // Reference first: fail with the transport error (not a weights error)
    // when Ollama isn't up.
    let reference = match ollama_greedy(&raw, MAX_TOKENS) {
        Ok(r) => r,
        Err(e) => panic!("Ollama reference unavailable: {e}"),
    };

    let tok = Tokenizer::from_file(dir.join("tokenizer.json")).expect("tokenizer.json loads");
    let prompt_ids = tok
        .encode(raw.as_str(), false)
        .expect("encodes")
        .get_ids()
        .to_vec();

    let device = burn::tensor::Device::<Gpu>::default();
    let loaded = qwen2::load_from_dir::<Gpu>(&dir, &device).expect("weights load checked");
    let ids = loaded
        .greedy_generate(&prompt_ids, MAX_TOKENS, &device)
        .expect("greedy decode");
    let ours = tok.decode(&ids, true).expect("decode");

    eprintln!("[parity/qwen2] ours   ({} tokens): {ours:?}", ids.len());
    eprintln!("[parity/qwen2] ollama            : {reference:?}");

    // Exact-match the greedy prefix over the shorter of the two (EOS/num_predict
    // may truncate one side earlier than the other).
    let n = ours.trim().len().min(reference.trim().len());
    assert!(n >= 8, "outputs too short to compare: {n} chars");
    assert_eq!(
        &ours.trim()[..n],
        &reference.trim()[..n],
        "greedy sequences diverge"
    );
}
